FROM mcr.microsoft.com/dotnet/core/sdk:2.2.203-alpine3.9

ENV ASPNETCORE_URLS=http://*:8080

RUN apk update && apk add --no-cache ca-certificates && rm -rf /var/cache/apk/*
RUN apk add --no-cache curl